### ISSUE TITLE
Can you add .tex files please?

### ISSUE THREAD

**Issue by DesBw** [Meep-Tech/obsidian-custom-file-extensions-plugin#1]
I installed this plugin and it is not able to load.

**Comment by MeepTech** [comment]
@Dellu 
You should be able to add tex in the settings via json format here:
![image](https://user-images.githubusercontent.com/54516780/236693528-d0c64a30-4260-48a4-b7da-3adbe7a59563.png)

just add: `, "tex"` after `"scss"`
