### ISSUE TITLE
Headings are not shown in outline (for rmarkdown)

### ISSUE THREAD

**Issue by pascalsiemsen** [Meep-Tech/obsidian-custom-file-extensions-plugin#4]
Love the plugin, as I can edit rmarkdown files in obsidian. 

But the outline (core plugin) does not show the headings. Syntax highlighting and everything else works. Also, plugins like Quick Switcher++ do not get the tags etc.

![2023-07-24-092454_hyprshot](https://github.com/MeepTech/obsidian-custom-file-extensions-plugin/assets/36855562/5cdcbdc4-0c28-4d5a-a3e7-ab7dc50866d9)

Could that be fixed? Or does the problem lie elsewhere?

**Comment by MeepTech** [comment]
I'm guessing this is because obsidian itself only scans `.md` files for metadata. My plugin only allows custom filetypes to be associated to views sadly. It's likely obsidian's api doesn't support this yet as well.
