### ISSUE TITLE
Why is the list of file extensions case sensitive and not case insensitive

### ISSUE THREAD

**Issue by roey-angel** [Meep-Tech/obsidian-custom-file-extensions-plugin#5]
As far as I know, operating systems usually treat file extensions as case insensitive; why is it not the case here?
This is particularly annoying with R since suffixes such as rmd, Rmd, and RMD are used interchangeably.

**Comment by MeepTech** [comment]
This is a limitation of obsidian sadly, as the only api method if offers uses case sensitivity; but I'll add a feature to include case insensitivity if needed by iterating all options.
